### ISSUE TITLE
KeePass 2.54 Dev. crashes when trying to open the context menu

### ISSUE THREAD

**Issue by ArtyoZ** [Rookiestyle/AdvancedAutoType#14]
## Overview
Hello, AdvancedAutoType plugin crashes the latest DEV builds of KeePass.

## Steps to Reproduce
1. Right click (or press Shift+F10) on any record in a listbox.

## Expected Behavior
Showing of context menu.

## Actual Behavior
Crashing of KeePass.

## Context
OS: Windows 10 x64 21H1
KeePass Version: 2.54 Dev. 230918 (64 bit)
Plugin Version: 2.1

[AAT_crashlog.txt](https://github.com/Rookiestyle/AdvancedAutoType/files/12735411/AAT_crashlog.txt)

**Comment by Rookiestyle** [comment]
Please post the link to the dev snapshot, they are not published along with the official releases

**Comment by ArtyoZ** [comment]
As far as I remember, crashes began with the first DEV KeePass builds after the 2.54 official release, not with the last one.

**Comment by Rookiestyle** [comment]
Please try the new release

**Comment by ArtyoZ** [comment]
> Please try the new release

Crashes has gone, everything is OK now. Thank you for a quick hotfix!
