### ISSUE TITLE
Add shortcut for TOTP auto type

### ISSUE THREAD

**Issue by ld892012** [Rookiestyle/AdvancedAutoType#18]
Hello,
It could be very useful if your extension have an custom shortcut for typing TOTP, KeePass uses `{TIMEOTP}` field for this value

**Comment by Rookiestyle** [comment]
My plugin  [KeePassOTP](/Rookiestyle/KeePassOTP) offers advanced features for TOTP and it allows you to define a shortcut for that as well.
