### ISSUE TITLE
Shortcut compatibility with Linux?

### ISSUE THREAD

**Issue by schklom** [Rookiestyle/AdvancedAutoType#19]
## Summary
On Linux distributions, shortcuts need to be added to the system manually (https://keepass.info/help/v2/setup.html#mono and https://keepass.info/help/base/cmdline.html) by e.g. setting Ctrl+Alt+A to `mono /YourPathToKeePass/KeePass.exe --auto-type` and Ctrl+Alt+Shift+A to `mono /YourPathToKeePass/KeePass.exe --auto-type-password`.

Can this plugin make it possible to add a shortcut in a similar way, by making it so that e.g. `mono /YourPathToKeePass/KeePass.exe --advanced-auto-type` calls your plugin's AutoType?

## Added value
People using Linux with KeePass could use your plugin.

**Comment by Rookiestyle** [comment]
Please test the attached version and use it like this `mono /YourPathToKeePass/KeePass.exe --e:advanced-auto-type` 
[AdvancedAutoType.zip](https://github.com/user-attachments/files/16381785/AdvancedAutoType.zip)

**Comment by schklom** [comment]
Sorry for the delay. It seems to only offer to autotype everything before `{AAT}`.
For example `{USERNAME}{AAT}{TOTP}` always offers to autotype `{USERNAME}`.

**Comment by Rookiestyle** [comment]
Please try again.

If it works, let me know :)
If it does not work, save the created debug file as .txt and attach it
[AdvancedAutoType.zip](https://github.com/user-attachments/files/17017620/AdvancedAutoType.zip)

**Comment by Rookiestyle** [comment]
Yes, that's the intended way.
Thanks for testing, I'll release the new version soon (debug mode being inactive then)
